<?php
namespace Ecommerce\EcommerceBundle\Twig\Extension;

class MontantTvaExtension extends \Twig_Extension
{


    /**
     * Returns the name of the extension.
     *
     * @return string The extension name
     */
    public function getName()
    {

        // TODO: Implement getName() method.
        return 'montant_tva_extention';
    }

    public function getFilters()
    {

        //parent::getFilters(); // TODO: Change the autogenerated stub

        return array(new  \Twig_SimpleFilter('montantTva', array($this, 'montantTva')));
    }


    public function montantTva($prixHt, $tva)
    {

        return round((($prixHt / $tva) - $prixHt), 2);
    }

}