<?php
namespace Ecommerce\EcommerceBundle\Twig\Extension;

class TvaExtension extends \Twig_Extension
{


    /**
     * Returns the name of the extension.
     *
     * @return string The extension name
     */
    public function getName()
    {

        // TODO: Implement getName() method.
        return 'tva_extention';
    }

    public function getFilters()
    {

        //parent::getFilters(); // TODO: Change the autogenerated stub

        return array(new  \Twig_SimpleFilter('tva', array($this, 'calculTva')));
    }


    public function calculTva($prixHt, $tva)
    {

        return round($prixHt / $tva, 2);
    }

}