adminCommandes:
    pattern:  /
    defaults: { _controller: "EcommerceBundle:CommandeAdmin:commandes" }

adminShowFacture:
    pattern:  /facture/{id}
    defaults: { _controller: "EcommerceBundle:CommandeAdmin:showFacture" }