<?php
namespace Ecommerce\EcommerceBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormConfigBuilderInterface;


class RechercheType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        // TODO: Change the autogenerated stub

        $builder->add('recherche', 'text', array('attr' => array(
            'class' => "input-medium search-query",
            'label' => false)));

        parent::buildForm($builder, $options);
    }


    public function getName()
    {

        // TODO: Change the autogenerated stub

        return parent::getName('ecommerce_ecommercebundle_recherche');
    }


}
